// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using wedding_wishlist.Models;

namespace weddingwishlist.Migrations
{
    [DbContext(typeof(WishlistContext))]
    [Migration("20170825192322_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("wedding_wishlist.Models.Wish", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("NumberBought");

                    b.Property<int>("NumberWished");

                    b.Property<int>("Price");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Wishes");
                });
#pragma warning restore 612, 618
        }
    }
}
